### ISSUE TITLE
about grafana dashboard Variables

### ISSUE THREAD

**Issue by myselfghost** [divinity666/ruby-grafana-reporter#20]
**Describe the issue**
 i want to ask ,why the variables in request url like var-idc\var-DS_PROMETHEUS\var-system are not the same with  template file

**Application call**
```
https://monitor.xxxx.com/render/d-solo/wVCbu81nz?panelId=2&fullscreen=true&theme=light&timeout=60&var-DS_PROMETHEUS=Prometheus-10.156.128.93&var-job=consul-node-exporter&var-idc=tencent-cloud&var-environment=pro&var-system=quote&var-node=10.156.160.3%3A9100&var-template=a&from=1639981641000&to=1642573640000
```
**Template file (if applicable)**
 - filename: 
 - relevant part of template file:
```
grafana_panel_image:2[dashboard="wVCbu81nz",from="now-30d",to="now",DS_PROMETHEUS="Prometheus-cq",job="consul-node-exporter",idc="HKEX-TNS",system="ip-bss",environment="pro"]
```

**Environment (please complete the following information):**
 - OS [e.g. Windows 10]: Windows
 - Environment [e.g. source, gem, docker or windows-exe]:  Windows-exe
 - ruby Version, if source or gem environment [e.g. 2.3.7]: 
 - reporter Version [e.g. 0.3.0]:0.5.1

**Comment by divinity666** [comment]
In your template file, you need to specify the variables like `var-DS_PROMETHEUS` instead of `DS_PROMETHEUS`. Otherwise the variables will not be forwarded to your rendering request.

Your call should look like:

`grafana_panel_image:2[dashboard="wVCbu81nz",from="now-30d",to="now",var-DS_PROMETHEUS="Prometheus-cq",var-job="consul-node-exporter",var-idc="HKEX-TNS",var-system="ip-bss",var-environment="pro]`

Please close the issue, if it is resolved.

**Comment by myselfghost** [comment]
> In your template file, you need to specify the variables like `var-DS_PROMETHEUS` instead of `DS_PROMETHEUS`. Otherwise the variables will not be forwarded to your rendering request.
> 
> Your call should look like:
> 
> `grafana_panel_image:2[dashboard="wVCbu81nz",from="now-30d",to="now",var-DS_PROMETHEUS="Prometheus-cq",var-job="consul-node-exporter",var-idc="HKEX-TNS",var-system="ip-bss",var-environment="pro]`
> 
> Please close the issue, if it is resolved.

thanks
