### ISSUE TITLE
Unable to select a theme when running as a webservice

### ISSUE THREAD

**Issue by hvostail** [divinity666/ruby-grafana-reporter#6]
Hello,

It would be good to have a possibility to pass the name of the theme inside the URL when running as a webservice, example:

[http://127.0.0.1:8815/render?var-template=demo_report&var-theme=demo_theme](url)

Perhaps, you could include similar functionality in the upcoming releases?

**Comment by divinity666** [comment]
Hi,

this is already possible. You can use an URL specifying the respective [asciidoctor variables](https://github.com/asciidoctor/asciidoctor-pdf/blob/main/docs/theming-guide.adoc#applying-your-theme). So your URL would look like:

http://127.0.0.1:8815/render?var-template=demo_report&pdf-theme=demo_theme

So the variable needs to be names **pdf-theme** instead of **var-theme**. Keep in mind that in this example the theme file is configured without `.yml`, i.e. the file has to be named that way as well.

Please confirm.

**Comment by hvostail** [comment]
Hello,

thanks, this is fine with me.
